// <auto-generated />
namespace CamposDealer_Teste_Back.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixdecimalonvalor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixdecimalonvalor));
        
        string IMigrationMetadata.Id
        {
            get { return "202206162205338_fix decimal on valor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
